const PermissionToMenu = {
    "DASHBOARD_ETABLISSEMENT": "Tableau de bord établissement",
    "ACTIVITY_LOGS": "Journal d’activité (logs)",
    "SESSIONS_CONNECTIONS": "Sessions & connexions",
    "MANAGE_LEVELS": "Gestion des niveaux",
    "MANAGE_STREAMS": "Gestion des filières (si utilisée)",
    "IMPORT_STUDENTS": "Importation élèves (Excel/CSV)",
    "STUDENT_DOSSIER": "Dossier élève (fiche individuelle)",
    "HARMONIZE_GRADES": "Harmonisation des notes",
    "VALIDATE_GRADES": "Validation des notes par chef d’établissement",
    "ACADEMIC_STATS": "Statistiques de réussite scolaire",
    "GRADES_COMPLETION_RATE": "Taux de complétion des notes",
    "GLOBAL_ATTENDANCE": "Présences / Absences globales",
    "ATTENDANCE_CERTIFICATE": "Attestation de fréquentation",
    "EXPORT_PDF_CLASS": "Export PDF de classe / matière",
    "MANAGE_SEQUENCES": "Séquences",
    "MANAGE_TERMS": "Trimestres",
    "MANAGE_PERIODS": "Périodes",
    "MANAGE_SUB_PERIODS": "Sous périodes",
    "MANAGE_USERS": "Utilisateurs",
    "BACKUP_DB": "Sauvegarder BD",
    "RESTORE_DB": "Restaurer BD",
    "LOAD_MENUS": "Charger menus",
    "EDIT_OWN_ACCOUNT": "Modification de son compte",
    "MANAGE_CYCLES": "Cycle/Section",
    "MANAGE_CLASSES": "Classe",
    "MANAGE_ROOMS": "Salle de classe",
    "MANAGE_PAYMENT_MODES": "Mode paiement",
    "MANAGE_BANKS": "Banque",
    "MANAGE_NEIGHBORHOODS": "Quartier/Secteur",
    "MANAGE_MONTHS": "Mois",
    "TRANSPORT_RATES": "Tarifs mensuels Transport",
    "MANAGE_FUNCTIONS": "Fonction",
    "MANAGE_GRADES": "Grade",
    "MANAGE_STAFF": "Enseignant/Personnel",
    "PAY_OTHER_FEES": "Paiement autres frais",
    "PAY_TRANSPORT": "Paiement transport",
    "MANAGE_JUSTIFICATIONS": "Justifications",
    "GRADES_REPORT_SHEET": "Fiche de report des notes",
    "PRINT_ANNUAL_REPORT_CARDS": "Impression bulletins Annuel",
    "PRINT_STUDENT_CARDS": "Cartes Scolaire par salle de classe",
    "FINANCIAL_BALANCE_SHEET": "Bilan des encaissements",
    "ROOM_EFFECTIVE": "Effectif/Salle de classe",
    "TUITION_BALANCE_SHEET": "Bilan frais scolaires",
    "OTHER_FEES_BALANCE_SHEET": "Bilan autres frais",
    "TRANSPORT_BALANCE_SHEET": "Bilan transports",
    "EXIT_SLIP": "Bordereau de Sortie/Quartier",
    "STAFF_PLACEMENT": "Mise en place du personnel",
    "CALCULATOR": "Calculatrice",
    "ABOUT": "A propos de...",
    "SUMMARY": "Sommaire...",
    "WEB_VERSION": "Version Web",
    "CHOOSE_BUTTON": "Bouton choisir",
    "NEW_OLD_EFFECTIVE": "Effectif Nouveau/Ancien",
    "GLOBAL_TUITION_STATUS": "Etat global des encaissements des frais scolaires par classe",
    "MANAGE_SANCTIONS": "Sanctions",
    "PERMISSION_REASONS": "Motifs de permission",
    "CYCLE_EFFECTIVE_HISTOGRAM": "Histogramme des effectifs/Cycle",
    "GENERAL_CONFIG": "Configuration generale",
    "MANAGE_TUTORSHIP": "Tutelle"
};

module.exports = PermissionToMenu;
