// constants/roles.js
// Synchronized with AcademicRole in Roles.kt
module.exports = {
  ADMINISTRATEUR: "ADMINISTRATEUR",
  FONDATEUR: "FONDATEUR",
  DIRECTEUR: "DIRECTEUR",
  VICE_PRINCIPAL: "VICE_PRINCIPAL",
  DIRECTEUR_DES_ETUDES: "DIRECTEUR_DES_ETUDES",
  INTENDANT: "INTENDANT",
  SECRETAIRE: "SECRETAIRE",
  SURVEILLANT_GENERAL: "SURVEILLANT_GENERAL",
  CHEF_DE_DEPARTEMENT: "CHEF_DE_DEPARTEMENT",
  ENSEIGNANT: "ENSEIGNANT",
  CONSEILLER_ORIENTATION: "CONSEILLER_ORIENTATION",
  INFIRMIER: "INFIRMIER",
  PARENT: "PARENT",
  ELEVE: "ELEVE",
  AGENT_ENTRETIEN: "AGENT_ENTRETIEN",
  PERSONNEL_CANTINE: "PERSONNEL_CANTINE"
};
